### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by gingerbeardman** [cinematicme/TwitterMarketingBlock#1]
I see this

![58419400-6c255300-8082-11e9-87ad-3b0cc0c09ffd](https://user-images.githubusercontent.com/49612/58419540-cf16ea00-8082-11e9-8e37-bb509a4227e2.png)

**Comment by coffeekomrade** [comment]
https://www.makeuseof.com/tag/share-import-twitter-block-lists/

**Comment by gingerbeardman** [comment]
That option has been removed in the "new twitter" redesign.

**Comment by coffeekomrade** [comment]
I just checked the flow through the website. It's Settings and Privacy > Blocked Accounts > Advanced (dropdown menu) > Import a List. Or the same steps as the article. Please try again with the provided steps.

**Comment by gingerbeardman** [comment]
I guess you are not using new twitter?

In new twitter, Settings and Privacy does not have Blocked Accounts.

I have to do Settings and Privacy > Content preferences > Blocked accounts, and then (as seen in my original screen) there is no Advanced or Import option.

I've taken this up with Twitter.

**Comment by coffeekomrade** [comment]
The “new” Twitter web UI is being rolled out to a small number of users as a beta test. Definitely best to take this up with twitter.
